name: Rust Lint

on:
  push:
    branches: ["main", "develop"]
    paths:
      - 'backend/**'
  pull_request:
    branches: ["main", "develop"]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Lint
      working-directory: ./backend
      run: |
        rustup component add clippy
        cargo clippy -- -D warnings

    - name: Format
      working-directory: ./backend
      run: cargo fmt
