name: Rust Test

on:
  push:
    branches: ["main", "develop"]
    paths:
      - 'backend/**'
  pull_request:
    branches: ["main", "develop"]


jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Test
      working-directory: ./backend
      run: cargo test --verbose
